### ISSUE TITLE
Base基类__destruct不应该主动close连接

### ISSUE THREAD

**Issue by webignorant** [Yurunsoft/YurunLock#3]
考虑以下情况，公用同一个redis资源时，如果销毁类时自动关闭，那么后续的会话存储就会出现问题了。
考虑类库的独立性，不要干涉用户资源的使用。

**Comment by webignorant** [comment]
@Yurunsoft 
参考https://github.com/webignorant/YurunLock/commit/109df4c3b34f7de0c86d7df680904b61c16b5173
似乎不小心提交到master了

Line186: $result = true;

**Comment by Yurunsoft** [comment]
之前忘记在close时候加判断，谢谢~已经提交
对了，要不要加个Q群，可以经常讨论交流，群号：74401592
