### ISSUE TITLE
可否支持 swoole 相关的异步框架

### ISSUE THREAD

**Issue by teg1c** [Yurunsoft/YurunLock#5]
rt.

**Comment by Yurunsoft** [comment]
Swoole 开启一键协程化后，可以支持文件操作、Redis的协程化，可以用的
<http://wiki.swoole.com/#/runtime>

**Comment by teg1c** [comment]
我用的hyperf框架，我想使用它的redis驱动。我看您这个貌似是直接链接的redos

**Comment by Yurunsoft** [comment]
是的，那也许只能你自己改造一下

**Comment by teg1c** [comment]
Ok
